version: "3"
services:
  server:
    build: server/
    command: node ./server.js
    ports:
      - "3000:3000"
    volumes:
      -  ./server:/server
      - /server:/src
    links: 
      - mongodb
  client:
    build: client/
    command: node ./client.js
    network_mode: host
    depends_on:
      - server
    volumes:
      - ./client:/client
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

